# About the Appendix  {.unnumbered}

The appendix consists of five sections. In [Appendix section 1](/appendix/#Shift-Invariant_Linear_Systems) I review several properties of shift-invariant linear systems and outline proofs of these properties. This appendix also includes a brief discussion of the Discrete Fourier Series, a method for representing functions as the weighted sum of harmonic functions. [Appendix section 2](/appendix/#Display_Calibration) contains a review of the main aspects of visual display calibration for psychophysical experiments. [Appendix section 3](/appendix/#Classification) contains a description of the basic results in classification theory, Bayes Rule and linear discriminant functions. [Appendix section 4](/appendix/#Signal_Estimation:_A_Geometric_View) provides a geometric interpretation of vector and matrix multiplication as well as a brief introduction to signal estimation. [Appendix section 5](/appendix/#Motion_Flow_Field_Calculation) outlines how to compute a motion flow field that arises when an observer moves through a fixed environment.